name: Build and publish

on:
  push:
    branches: [ master ]

env:
  SDK_VERSION: 6.0.x
  PACKAGE_1: Gandalan.IDAS.Crypto
  PACKAGE_2: Gandalan.IDAS.Logging
  PACKAGE_3: Gandalan.IDAS.WebApi.Client
  PACKAGE_4: Gandalan.IDAS.WebApi.Client.Wpf

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 50

    - name: Set release_name
      id: set_release_name
      run: echo "::set-output name=release_name::$(date +'%-Y.%-m.%-d').$GITHUB_RUN_NUMBER"
    - name: Setup .NET Core SDK ${{ env.SDK_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.SDK_VERSION }}
    - name: Run UpdateVersionInfo.ps1 with ${{ steps.set_release_name.outputs.release_name }}
      shell: pwsh
      run: .\UpdateVersionInfo.ps1 ${{ steps.set_release_name.outputs.release_name }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create package ${{ env.PACKAGE_1 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_1 }}.csproj
    - name: Create package ${{ env.PACKAGE_2 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_2 }}.csproj
    - name: Create package ${{ env.PACKAGE_3 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_3 }}.csproj
    - name: Create package ${{ env.PACKAGE_4 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_4 }}.csproj
    - name: Push packages
      run: dotnet nuget push "**/*.nupkg" -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: IDAS.Client.Libs-Release_${{ steps.set_release_name.outputs.release_name }}
    - name: Create release with changelog
      id: build_changelog
      uses: fregante/release-with-changelog@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: IDAS.Client.Libs-Release_${{ steps.set_release_name.outputs.release_name }}
        tag: IDAS.Client.Libs-Release_${{ steps.set_release_name.outputs.release_name }}
        prerelease: true
    # Waiting for https://github.com/fregante/release-with-changelog/pull/58
    #- name: Upload Assets to Release with a wildcard
      #uses: csexton/release-asset-action@v2
      #with:
        #pattern: "**/*.nupkg"
        #github-token: ${{ secrets.GITHUB_TOKEN }}
        #release-url: ${{ steps.create_release.outputs.upload_url }}
