name: Build and publish

on:
  push:
    branches: [ master ]
  pull_request: # for test only
    branches: [ master ]

env:
  SDK_VERSION: 6.0.x
  PACKAGE_1: Gandalan.IDAS.Crypto
  PACKAGE_2: Gandalan.IDAS.Logging
  PACKAGE_3: Gandalan.IDAS.WebApi.Client
  PACKAGE_4: Gandalan.IDAS.WebApi.Client.Wpf

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set release_name
      id: set_release_name
      run: echo "::set-output name=release_name::'$(date +'%-Y.%-m.%-d.') $GITHUB_RUN_NUMBER - ${ GITHUB_RUN_NUMBER } test'"
    - name: Test release_name
      run: echo ${{ steps.set_release_name.outputs.release_name }}
    - name: Setup .NET Core SDK ${{ env.SDK_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.SDK_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Create package ${{ env.PACKAGE_1 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_1 }}.nuspec
    - name: Create package ${{ env.PACKAGE_2 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_2 }}.nuspec
    - name: Create package ${{ env.PACKAGE_3 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_3 }}.nuspec
    - name: Create package ${{ env.PACKAGE_4 }}
      run: dotnet pack --configuration Release **/${{ env.PACKAGE_4 }}.nuspec
