name: Check WebLibs (NPM)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'WebLibs/**'
      - '.github/workflows/check-weblibs.yml'

env:
  WEBLIBS_DIR: WebLibs

jobs:
  check-weblibs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci
      working-directory: ${{ env.WEBLIBS_DIR }}
    - run: npm run svelte-check
      working-directory: ${{ env.WEBLIBS_DIR }}
    - run: npm run lint:prod
      working-directory: ${{ env.WEBLIBS_DIR }}
    - name: Send mail if job failed
      if: ${{ failure() && github.repository_owner == 'gandalan' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.MAIL_SERVER}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: GitHub Action failed for workflow '${{ github.workflow }}'!
        to: ${{ secrets.DEV_EMAIL }}
        from: GH Actions
        body: Job '${{ github.job }}' failed! Triggered by ${{ github.triggering_actor }}. Ref ${{ github.ref }}
