name: Check WebLibs (NPM)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'WebLibs/**'
      - '.github/workflows/check-weblibs.yml'

env:
  WEBLIBS_DIR: WebLibs

jobs:
  check-weblibs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm ci
      working-directory: ${{ env.WEBLIBS_DIR }}
    - run: npm run svelte-check
      working-directory: ${{ env.WEBLIBS_DIR }}
    - run: npm run lint:prod
      working-directory: ${{ env.WEBLIBS_DIR }}
